events {
    worker_connections 1024;
}

http {
    upstream java-backend {
        server fs-notification-backend:8085;
    }

    upstream vue-frontend {
        server fs-notification-frontend:80;
    }

    server {
        listen 80;
        listen 443;

        client_max_body_size 10M;

        location / {
            proxy_pass http://vue-frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/bot/ {
            proxy_pass http://java-backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}